force-app/main/default/objects/Cooking_Action__c/Cooking_Action__c.object-meta.xml
<CustomObject>
    <description>An action that is taken as part of a Recipe_Step when preparing a meal</description>
    <label>Cooking Action</label>
    <nameField>
        <label>Cooking Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cooking Action</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cooking_Action_on_Recipe_Step__c/Cooking_Action_on_Recipe_Step__c.object-meta.xml
<CustomObject>
    <description>Junction object facilitiating many-may relationship between cooking actions and recipe steps</description>
    <label>Cooking Action on Recipe Step</label>
    <nameField>
        <displayFormat>CSRN-{00000}</displayFormat>
        <label>Cooking Step on Recipe Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cooking Actions on Recipe Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cooking_Action_on_Recipe_Step__c/fields/Cooking_Action__c.field-meta.xml
<CustomField>
    <fullName>Cooking_Action__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cooking Action</description>
    <inlineHelpText>Cooking Action</inlineHelpText>
    <label>Cooking Action</label>
    <referenceTo>Cooking_Action__c</referenceTo>
    <relationshipLabel>Recipe Steps with Cooking Action</relationshipLabel>
    <relationshipName>Recipe_Steps_with_Cooking_Action</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cooking_Action_on_Recipe_Step__c/fields/Recipe_Step__c.field-meta.xml
<CustomField>
    <fullName>Recipe_Step__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Recipe Step</description>
    <inlineHelpText>Recipe Step</inlineHelpText>
    <label>Recipe Step</label>
    <referenceTo>Recipe_Step__c</referenceTo>
    <relationshipLabel>Cooking Actions on Recipe Steps</relationshipLabel>
    <relationshipName>Cooking_Actions_on_Recipe_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recipe_Step__c/Recipe_Step__c.object-meta.xml
<CustomObject>
    <description>A set of actions taken on one/many ingredients in sequence in order to prepare a recipe</description>
    <label>Recipe Step</label>
    <nameField>
        <displayFormat>STEP-{00000}</displayFormat>
        <label>Recipe Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recipe Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Recipe_Step__c/fields/Step_Summary__c.field-meta.xml
<CustomField>
    <fullName>Step_Summary__c</fullName>
    <description>Summary of Recipe Step</description>
    <inlineHelpText>Summary of Recipe Step</inlineHelpText>
    <label>Step Summary</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/RecipeStepUtils.cls
public with sharing class RecipeStepUtils {
  public RecipeStepUtils() {
  }

  //parse recipe step text, identify related cooking actions and create junction object as needed.
  @InvocableMethod
  public static void relateCookingActions(List<Recipe_Step__c> rList) {
    Map<String, Cooking_Action__c> cMap = getAllCookingActions();

    Map<Id, List<Cooking_Action_on_Recipe_Step__c>> carsMap = getCarsMap(rList);

    createCars(rList, cMap, carsMap);
  }

    //Get Map of all Cooking Actions
  public static Map<String, Cooking_Action__c> getAllCookingActions() {
    List<Cooking_Action__c> cList = [SELECT Id, Name FROM Cooking_Action__c];
    Map<String, Cooking_Action__c> cMap = new Map<String, Cooking_Action__c>();
    for (Cooking_Action__c c : cList) {
      cMap.put(c.Name.toLowerCase(), c);
    }
    return cMap;
  }

    //Get Map of Existing Cooking Action on Recipe Step records
  public static Map<Id, List<Cooking_Action_on_Recipe_Step__c>> getCarsMap(
    List<Recipe_Step__c> rList
  ) {
    List<Cooking_Action_on_Recipe_Step__c> carsList = [
      SELECT Id, Cooking_Action__r.Name, Recipe_Step__c
      FROM Cooking_Action_on_Recipe_Step__c
      WHERE Recipe_Step__c IN :rList
    ];
    Map<Id, List<Cooking_Action_on_Recipe_Step__c>> carsMap = new Map<Id, List<Cooking_Action_on_Recipe_Step__c>>();
    for (Recipe_Step__c r : rList) {
      carsMap.put(r.Id, new List<Cooking_Action_on_Recipe_Step__c>());
    }
    for (Cooking_Action_on_Recipe_Step__c cars : carsList) {
      carsMap.get(cars.Recipe_Step__c).add(cars);
    }
    return carsMap;
  }

  //Create Cooking Action on Recipe Step Records as needed
  public static void createCars(
    List<Recipe_Step__c> rList,
    Map<String, Cooking_Action__c> cMap,
    Map<Id, List<Cooking_Action_on_Recipe_Step__c>> carsMap
  ) {
    List<String> cookingActions = new List<String>();
    List<String> stepSummaryParse = new List<String>();
    Map<String, Cooking_Action__c> matchCMap = new Map<String, Cooking_Action__c>();
    List<Cooking_Action_on_Recipe_Step__c> insertCARSList = new List<Cooking_Action_on_Recipe_Step__c>();

    for (Recipe_Step__c r : rList) {
      System.debug(r);
      //parse step summary into words
      stepSummaryParse = r.Step_Summary__c.remove('.').remove(',').split(' ');
      //check if any of those words match a cooking action
      for (String s : stepSummaryParse) {
        s = s.trim().toLowerCase();
        if (cMap.get(s) != null) {
          matchCMap.put(s, cMap.get(s));
        }
      }
      //check if matching cooking actions have a junction record and remove from matchList
      for (Cooking_Action_on_Recipe_Step__c c : carsMap.get(r.Id)) {
        matchCMap.remove(c.Cooking_Action__r.Name);
      }
      //if no match, create a junction record.
      for (String key : matchCMap.keySet()) {
        Cooking_Action_on_Recipe_Step__c newCARS = new Cooking_Action_on_Recipe_Step__c(
          Cooking_Action__c = matchCMap.get(key).Id,
          Recipe_Step__c = r.Id
        );
        insertCARSList.add(newCARS);
      }
      //clear stepSummaryParse, temp and cookingActions
      stepSummaryParse.clear();
      cookingActions.clear();
      matchCMap.clear();
    }

    doInsertCARSList(insertCARSList);
  }
  
  //insert records to database and debug errors
  public static void doInsertCARSList(List<Cooking_Action_on_Recipe_Step__c> insertCARSList){
      List<Database.SaveResult> srList = Database.insert(insertCARSList, false);
    for (Database.SaveResult sr : srList) {
      if (sr.isSuccess() == false) {
        System.debug(sr.getErrors());
      }
    }
  }
}