force-app/main/default/objects/Recipe_Step__c/Recipe_Step__c.object-meta.xml
<CustomObject>
    <description>A set of actions taken on one/many ingredients in sequence in order to prepare a recipe</description>
    <label>Recipe Step</label>
    <nameField>
        <displayFormat>STEP-{00000}</displayFormat>
        <label>Recipe Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recipe Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Recipe_Step__c/fields/Step_Summary__c.field-meta.xml
<CustomField>
    <fullName>Step_Summary__c</fullName>
    <description>Summary of Recipe Step</description>
    <inlineHelpText>Summary of Recipe Step</inlineHelpText>
    <label>Step Summary</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/RecipeStepTriggerHandler.cls
public with sharing class RecipeStepTriggerHandler {
  public RecipeStepTriggerHandler() {
  }
  public static void beforeInsertHandler(List<Recipe_Step__c> triggerNew) {
  }
  public static void beforeUpdateHandler(
    Map<Id, Recipe_Step__c> triggerOldMap,
    Map<Id, Recipe_Step__c> triggerNewMap
  ) {
    RecipeStepUtils.relateCookingActions(
      getSummaryStepChangedList(triggerOldMap, triggerNewMap)
    );
  }
  public static void afterInsertHandler(List<Recipe_Step__c> triggerNew) {
    RecipeStepUtils.relateCookingActions(triggerNew);
  }

  //compare Summary_Step__c field and return list of records with changed values
  public static List<Recipe_Step__c> getSummaryStepChangedList(
    Map<Id, Recipe_Step__c> triggerOldMap,
    Map<Id, Recipe_Step__c> triggerNewMap
  ) {
    List<Recipe_Step__c> rList = new List<Recipe_Step__c>();
    for (Id key : triggerNewMap.keySet()) {
      if (
        triggerNewMap.get(key).Step_Summary__c !=
        triggerOldMap.get(key).Step_Summary__c
      ) {
        rList.add(triggerNewMap.get(key));
      }
    }
    return rList;
  }
}